### ISSUE TITLE
Java API运行报错 

### ISSUE THREAD

**Issue by FrostN0v0** [WindrunnerMax/SW#26]
Exception in thread "main" java.lang.NullPointerException
	at com.sw.MainSw.<init>(MainSw.java:44)
	at com.sw.MainSw.main(MainSw.java:118)
小白问一下什么原因 如何解决

**Comment by WindRunnerMax** [comment]
你们学校开了`api`了吗，要不你试试`python`版本的那个

**Comment by FrostN0v0** [comment]
python版本可用，测试用的就是山科的强智

**Comment by FrostN0v0** [comment]
希望可用测试（如果有问题）并修复一下java版本的api

**Comment by WindRunnerMax** [comment]
修复了，看一下

**Comment by FrostN0v0** [comment]
可以了，感谢
